apiVersion: apps/v1 # A bucket of different Objects (pods, services, deployments)
kind: Deployment
metadata:
  name: posts-depl
spec: # How this deployment should behave
  replicas: 1 # The number of pods that we want running some image

  ## Selector and template work together & tells this deployment which pods it should be managing 
  selector:
    matchLabels:
      app: posts # Look for the pods with label { app: posts } matchLabels are key-value pairs.

  ## Templates are pod configuration -- pretty much a pod config file
  template: 
    metadata:
      labels:
        app: posts #we want the pods to have a label { app: posts }
    spec:
      containers: 
        - name: posts
          image: chelsejw/posts # THe docker image; it will try to use the latest image

---


apiVersion: v1
kind: Service
metadata:
  name: posts-clusterip-srv
spec:
  selector: # The pods you want to expose, corresponding to their label eg { app: posts }
    app: posts
  type: ClusterIP # if not specified, it will default to ClusterIP - so this line is not needed
  ports:
    - name: posts
      protocol: TCP
      port: 4000
      targetPort: 4000
