apiVersion: v1
kind: Service
metadata:
  name: posts-srv
spec:
  type: NodePort # the type of Service
  selector: # The pods you want to expose, corresponding to their label eg { app: posts }
    app: posts 
  ports:
    - name: posts 
      protocol: TCP
      port: 4000 # The NodePort services, which could re-direct traffic to another port running the container
      targetPort: 4000 # The final destination